# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: categorization.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63\x61tegorization.proto\"w\n\x0cTrainRequest\x12\x12\n\ntemplateId\x18\x01 \x01(\t\x12!\n\x05items\x18\x02 \x03(\x0b\x32\x12.TrainRequest.Item\x1a\x30\n\x04Item\x12\x14\n\x0c\x63\x61tegoryName\x18\x01 \x01(\t\x12\x12\n\nentityName\x18\x02 \x01(\t\" \n\rTrainResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2:\n\x0e\x43\x61tegorization\x12(\n\x05Train\x12\r.TrainRequest\x1a\x0e.TrainResponse\"\x00\x42)\xaa\x02&YLists.Categorization.Client.Generatedb\x06proto3')



_TRAINREQUEST = DESCRIPTOR.message_types_by_name['TrainRequest']
_TRAINREQUEST_ITEM = _TRAINREQUEST.nested_types_by_name['Item']
_TRAINRESPONSE = DESCRIPTOR.message_types_by_name['TrainResponse']
TrainRequest = _reflection.GeneratedProtocolMessageType('TrainRequest', (_message.Message,), {

  'Item' : _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), {
    'DESCRIPTOR' : _TRAINREQUEST_ITEM,
    '__module__' : 'categorization_pb2'
    # @@protoc_insertion_point(class_scope:TrainRequest.Item)
    })
  ,
  'DESCRIPTOR' : _TRAINREQUEST,
  '__module__' : 'categorization_pb2'
  # @@protoc_insertion_point(class_scope:TrainRequest)
  })
_sym_db.RegisterMessage(TrainRequest)
_sym_db.RegisterMessage(TrainRequest.Item)

TrainResponse = _reflection.GeneratedProtocolMessageType('TrainResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRAINRESPONSE,
  '__module__' : 'categorization_pb2'
  # @@protoc_insertion_point(class_scope:TrainResponse)
  })
_sym_db.RegisterMessage(TrainResponse)

_CATEGORIZATION = DESCRIPTOR.services_by_name['Categorization']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002&YLists.Categorization.Client.Generated'
  _TRAINREQUEST._serialized_start=24
  _TRAINREQUEST._serialized_end=143
  _TRAINREQUEST_ITEM._serialized_start=95
  _TRAINREQUEST_ITEM._serialized_end=143
  _TRAINRESPONSE._serialized_start=145
  _TRAINRESPONSE._serialized_end=177
  _CATEGORIZATION._serialized_start=179
  _CATEGORIZATION._serialized_end=237
# @@protoc_insertion_point(module_scope)
